services:
  proxy:
    image: nginx:1.29-alpine
    container_name: llama-swap-service-reverse-proxy
    ports:
      - "10999:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/api_keys.conf:/etc/nginx/api_keys.conf
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd
    restart: unless-stopped
